### ISSUE TITLE
ctf-tools?

### ISSUE THREAD

**Issue by zardus** [mahaloz/pwnbox#1]
ctf-tools!

**Comment by mahaloz** [comment]
you make a good point

**Comment by mahaloz** [comment]
but ctf-tools required users to install all of the things they needed--nor did it give them an absolutely sick terminal setup

**Comment by zardus** [comment]
Oh, I agree that the box is great. My suggestion is to add ctf-tools to the env as well; that way the tools are a simple command away.

**Comment by mahaloz** [comment]
Alright, deal.

**Comment by mahaloz** [comment]
Added https://github.com/pwndevils/pwnbox/commit/dda09ae52e7e5a2f9ec48d97647861b66f767630
prepare for a large gig update lol...
